/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Campus {
  createdAt: Timestamp;
  id: string;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string;
}

export interface CampusInvitation {
  campusId: string;
  createdAt: Generated<Timestamp>;
  email: string;
  expiresAt: Timestamp;
  id: string;
  inviterId: string;
  role: string | null;
  status: string;
}

export interface CampusMember {
  campusId: string;
  createdAt: Timestamp;
  id: string;
  role: string;
  userId: string;
}

export interface CampusRole {
  campusId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  permission: string;
  role: string;
  updatedAt: Timestamp | null;
}

export interface Department {
  campusId: string | null;
  id: string;
  name: string | null;
  slug: string | null;
}

export interface Platform {
  id: number;
  initialized: Generated<boolean>;
  initializedAt: Timestamp | null;
  initializedBy: string | null;
}

export interface Session {
  activeCampusId: string | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  impersonatedBy: string | null;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface User {
  banExpires: Timestamp | null;
  banned: boolean | null;
  banReason: string | null;
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  role: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  campus: Campus;
  campusInvitation: CampusInvitation;
  campusMember: CampusMember;
  campusRole: CampusRole;
  department: Department;
  platform: Platform;
  session: Session;
  user: User;
  verification: Verification;
}
